[project]
name = "LSH-implementation"
version = "1.0.0"
authors = [
    {name = "David Hanny", email = "david.hanny@stud.sbg.ac.at"},
]
description = "Implementation of locality-sensitive hashing for string documents."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "xxhash",
]